name: Auto Update Code with Gemini

on:
  schedule:
    - cron: '0 * * * *'  # Запуск каждый час
  push:
    branches:
      - main

jobs:
  update_code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run analysis and update code
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python src/main.py

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add src/model_training.py report.md
          COMMIT_MESSAGE=$(python src/commit_message.py)
          git commit -m "$COMMIT_MESSAGE" || echo "No changes to commit"
          git push origin main
