name: Auto Update Code with Gemini

on:
  schedule:
    - cron: '0 * * * *'  # Запуск каждый час
  push:
    branches:
      - main

jobs:
  update_code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "requirements.txt not found!" && exit 1
          fi

      - name: Verify API Key
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          if [ -z "$GEMINI_API_KEY" ]; then
            echo "❌ API-ключ для Gemini отсутствует! Проверьте GitHub Secrets."
            exit 1
          else
            echo "✅ API-ключ загружен, длина: ${#GEMINI_API_KEY} символов"
          fi

      - name: Run update script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python src/main.py

      - name: Show Git status
        run: git status

      - name: Show Git diff
        run: git diff

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          
          git add .
          
          if git diff --staged --quiet; then
            echo "No changes to commit."
            exit 0
          fi

          git commit -m "Auto-update commit"
          git push origin main
